name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: node:18-alpine3.15
    steps:
      - name: Log Our Node version
        run: |
          node -v 
          cat /etc/os-release/
