name: matrix
on: pull_request

jobs:
  node-version:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node_version: [6, 8, 10]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Log Node node version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-verion: ${{ matrix.node_version }}
      - name: Log Node version
        run: node -v
