name: matrix
on: push

jobs:
  node-version:
    steps:
      - name: Log Node node version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-verion: 6
      - name: Log Node version
        run: node -v
